# Generated by Django 4.1.7 on 2023-02-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='members',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
