# Generated by Django 4.1.7 on 2023-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unit_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
